---
title: "R Notebook"
output: html_notebook
---

```{r, results='hide'}
library(tidyverse)
library(readxl)
library(lme4)
library(lmerTest)
library(psych)
```


Find the datafiles

```{r, results='hide'}

list_of_performance_data <- list.files(path = "G:/Shared drives/Projects/2018 Driving Sim Reproducibility/4_Analysis_Saccades/Task Response Data", recursive = TRUE, full.names = TRUE)

Filename_Database <- read_excel("G:/Shared drives/Projects/2018 Driving Sim Reproducibility/File Reference Database.xlsx", sheet = 1)


Country_reference_database <- Filename_Database %>% 
    filter(Scenario == "Country")

find_task_csv_filename <- function(x) {
   y <- list.files(path = "G:\\Shared drives\\Projects\\2018 Driving Sim Reproducibility\\4_Analysis_Saccades\\Task Response Data", 
           pattern = paste0(x,"_Prosaccade_Results_var.csv"), 
           full.names = TRUE, recursive = TRUE)
  
 z <- if_else(length(y) == 0, "NA", y[1]) %>% as.character()
    z
}

Country_reference_database$Task_csvs <- Country_reference_database$Task_Pattern %>% lapply(find_task_csv_filename) %>% as.character()

importing_df <- Country_reference_database %>% select(Participant, Session, Run, Task_csvs)

read_csv(importing_df[1,4])

y <- importing_df[Task_csvs] %>% as.character()

importing_df
read_csv(y, col_names = taskresponse_colnames)
```

Import the data

```{r, results='hide'}


taskresponse_colnames <- c("trial number", "tTRIG", "tTIME", "tCorr", 
                            "Corr_tTIME", "rKey", "rSecs","rTIME", 
                            "rCorr", "Corr_rTIME", "rDir", "Condition" )

Task_csvs <- importing_df[1,5] %>% as.character()
Participant <- importing_df[1,1]
Session <- importing_df[1,2]
Run <-  importing_df[1,4]

raw_file <- read_csv(Task_csvs, col_names = taskresponse_colnames )

raw_file %>% group_by(response_type) %>% summarise(reaction_time = mean(reaction_time, na.rm = TRUE))

create_database_task_response <- function (Participant, Session, Run, Task_csvs) {
   
 taskresponse_colnames <- c("trial number", "tTRIG", "tTIME", "tCorr", 
                       "Corr_tTIME", "rKey", "rSecs","rTIME", 
                      "rCorr", "Corr_rTIME", "rDir", "Condition" )

 filename <- Task_csvs %>% as.character()   
  df <- read_csv(filename, col_names = taskresponse_colnames)
  df$ID <- Participant %>% as.character()
  df$Session <- Session %>% as.character()
  df$Run <- Run %>% as.character()
  
 df
}


task_response_database <- importing_df %>% 
    filter(Task_csvs != "NA") %>%
    pmap_df(~create_database_task_response(..1,..2,..3,..4))

print(importing_df)

```

Analysing the data

```{r}
task_response_database$task_condition <- ifelse(task_response_database$rDir == 2,
                                          task_response_database$Condition + 12, 
                                          task_response_database$Condition)
task_response_database$task_arrow_dir <- ifelse(task_response_database$rDir == 1, "Left", "Right")
task_response_database$stimulus_left_right <- ifelse(task_response_database$Condition <= 6, "Left", "Right")
task_response_database$reaction_time <- task_response_database$Corr_rTIME - task_response_database$Corr_tTIME
task_response_database$congruency <- ifelse(task_response_database$task_arrow_dir == task_response_database$stimulus_left_right, "Congruent", "Incongruent")
task_response_database$target_deviation <- ifelse(task_response_database$Condition %% 3 == 1, "10", 
                                            ifelse(task_response_database$Condition %% 3 == 2, "25",
                                                   ifelse(task_response_database$Condition %% 3 == 0, "35", NA))) %>% as.numeric()
task_response_database$response_type <- ifelse(task_response_database$rDir == task_response_database$rKey,"Correct",
                        ifelse((task_response_database$rKey == 0), "Miss",
                        ifelse((task_response_database$rKey > 0) & (task_response_database$rKey != task_response_database$rDir),"Incorrect", NA)))

session_levels <- c("F","1","2")
#summarised withouot congruency
wo_congruency <- task_response_database %>% group_by(ID, Session, Run) %>%
    summarise(percent_correct = mean(response_type == "Correct", na.rm = TRUE), 
                       percent_miss = mean(response_type == "Miss", na.rm = TRUE),
                       percent_incorrect = mean(response_type == "Incorrect", na.rm = TRUE),
              avg_reaction_time = mean(reaction_time, na.rm = T))
wo_congruency$Session <- wo_congruency$Session %>% factor(session_levels)
wo_congruency$Run <- wo_congruency$Run %>% as.factor()

wo_congruency2 <- wo_congruency %>% filter(Session != "F")
# sumarised by congruency
with_congruency <- task_response_database %>% group_by(ID, Session, Run, congruency) %>%
    summarise(percent_correct = mean(response_type == "Correct", na.rm = TRUE), 
                       percent_miss = mean(response_type == "Miss", na.rm = TRUE),
                       percent_incorrect = mean(response_type == "Incorrect", na.rm = TRUE))

save_filename <- file.choose()
write.csv(wo_congruency, save_filename)
```

sifting it down to each trial


```{r}

Fam   <- wo_congruency %>% filter(Session == "F" & Run == "1") %>% select(percent_correct)
S1_R1 <- wo_congruency %>% filter(Session == "1" & Run == "1") %>% select(percent_correct)
S1_R2 <- wo_congruency %>% filter(Session == "1" & Run == "2") %>% select(percent_correct)
S2_R1 <- wo_congruency %>% filter(Session == "2" & Run == "1") %>% select(percent_correct)
S2_R2 <- wo_congruency %>% filter(Session == "2" & Run == "2") %>% select(percent_correct)


formatted <- right_join(Fam, S1_R1, by = c("ID")) 
formatted





```



Statistical Analyses
```{r}

fit1 <- anova(lmer(percent_correct ~ Session + Run + (1|ID), data = wo_congruency))
fit1
summary(fit1)
aov(fit1)

plot1 <- wo_congruency %>% group_by(Session, Run) %>% summarise(percent_correct = mean(percent_correct) , 
                       percent_miss = mean(percent_miss),
                       percent_incorrect = mean(percent_incorrect)) %>%
    ggplot(aes(x = Run, y = percent_correct, colour = Session)) +
        geom_point() +
    ylim(0.7,1)

    
plot1



fit2 <- anova(lmer(percent_correct ~ Session + Run + congruency + (1|ID),data =  with_congruency))
fit2

    

ICC_import <- read.csv("G:\\Shared drives\\Projects\\2018 Driving Sim Reproducibility\\4_Analysis_Saccades\\ICC_to_import.csv")
ICC_ready <- ICC(ICC_import[-1,-2],missing = FALSE)
ICC_ready
ICC_output <- ICC_ready$results
ICC_import_noNS <- ICC_import %>% filter(ID != "NS")

across_all_but_fam <- ICC(ICC_import_noNS[c(-1,-2)],missing = T)
across_all_but_fam

between_sessions_R1 <- ICC(ICC_import[c(-1,-2,-4,-6)],missing = FALSE)
between_sessions_R1

between_sessions_R2 <- ICC(ICC_import[c(-1,-2,-3,-5)],missing = FALSE)
between_sessions_R2

within_session1 <- ICC(ICC_import[c(-1,-2,-5,-6)],missing = T)
within_session1

within_session2 <- ICC(ICC_import[c(-1,-2,-3,-4)],missing = FALSE)
within_session2
```

