---
title: "Demo of Effect of hypoxia"
author: "Hayden Green"
date: "24/05/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(signal)
library(cowplot)

```



```{r}

id_list <- c("CC_6","CC_8","CC_10")
trial <- c("normoxia", "hypoxia1","hypoxia2")

direct <- choose.dir()
file_to_load <- list.files(path = direct, pattern = paste0(id_list[1],"_checked.csv"), recursive = TRUE, full.names = TRUE)

checked_csv <- read_csv(file_to_load)

bfhigh <- butter(1, c(0,0.1), type = "high")
checked_csv <- checked_csv %>%
               dplyr::filter(Total_dist > 900) %>% 
               mutate(filtered_speed = filter(bfhigh,Speed), filtered_lane_pos = filter(bfhigh,Lateral_Lane_Pos + 6), condition = "normoxia")

cc_6 <- list.files(path = direct, pattern = paste0(id_list[1],"_checked.csv"), recursive = TRUE, full.names = TRUE) %>%
        read_csv() %>%
        dplyr::filter(Total_dist > 900) %>% 
               mutate(filtered_speed = filter(bfhigh,Speed), filtered_lane_pos = filter(bfhigh,Lateral_Lane_Pos + 6), condition = "normoxia")
    
cc_8 <- list.files(path = direct, pattern = paste0(id_list[2],"_checked.csv"), recursive = TRUE, full.names = TRUE) %>%
        read_csv() %>%
        dplyr::filter(Total_dist > 900) %>% 
               mutate(filtered_speed = filter(bfhigh,Speed), filtered_lane_pos = filter(bfhigh,Lateral_Lane_Pos + 6), condition = "hypoxia1")

cc_10 <- list.files(path = direct, pattern = paste0(id_list[3],"_checked.csv"), recursive = TRUE, full.names = TRUE) %>%
        read_csv() %>%
        dplyr::filter(Total_dist > 900) %>% 
               mutate(filtered_speed = filter(bfhigh,Speed), filtered_lane_pos = filter(bfhigh,Lateral_Lane_Pos + 6), condition = "hypoxia2")

working_data <- cc_6 %>% full_join(cc_8) %>% full_join(cc_10)

```

```{r}
unfiltered_lanepos_plot <- working_data %>% 
                         ggplot(aes(x= Total_dist, y = Lateral_Lane_Pos +6, 
                                    colour = condition)) + 
                         geom_line() +
                         ylab("Lateral Lane Position (m)")+
                         theme_classic()
unfiltered_lanepos_plot

filtered_lanepos_plot <- working_data %>% 
                         ggplot(aes(x= Total_dist, y = filtered_lane_pos,
                                    colour = condition)) + 
                         geom_line() +
                         ylab("Lateral Lane Position (m)")+
                         ylim(-0.2,0.2)+
                         theme_classic()

plot_grid(unfiltered_lanepos_plot, filtered_lanepos_plot, labels =  c("Lane Pos Unfiltered","Lane Pos 0.1HZ Filtered"), scale = 1)

```


```{r}
working_data %>% dplyr::filter(Total_dist < 30000) %>% group_by(condition) %>% 
    summarise(mean(Speed),sd(Speed),
              mean_lane_pos = mean(Lateral_Lane_Pos+6),
              sd_lane_pos = sd(Lateral_Lane_Pos+6),
              mean(filtered_speed),
              sd(filtered_speed), 
              mean_filt_lane = mean(filtered_lane_pos),
              sd_filt_lane = sd(filtered_lane_pos))



```

```{r}

unfiltered_lanepos_boxplot <- working_data %>% 
                         ggplot(aes(x= Total_dist, y = Lateral_Lane_Pos +6, 
                                    colour = condition)) + 
                         geom_boxplot() +
                         ylab("Lateral Lane Position (m)")+
                         theme_classic()


filtered_lanepos_boxplot <- working_data %>% 
                         ggplot(aes(x= Total_dist, y = filtered_lane_pos,
                                    colour = condition)) + 
                         geom_boxplot() +
                         ylab("Lateral Lane Position (m)")+
                         theme_classic()

plot_grid(unfiltered_lanepos_boxplot, filtered_lanepos_boxplot, labels =  c("Lane Pos Unfiltered","Lane Pos 0.1HZ Filtered"), scale = 1)
```

