---
title: "Final Analysis"
author: "Hayden Green"
date: "3 April 2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}

library(tidyverse)
library(readxl)
library(lme4)
library(lmerTest)
library(psych)
library(ggplot2)
library(ggthemes)
library(ggridges)
library(ez)
library(broom)
```

## R Markdown


```{r results='hide', warning=FALSE, error=FALSE}

saccades_database <- read_csv("G:\\Team Drives\\Research Team\\Projects\\2018 Driving Sim Reproducibility\\4_Analysis_Saccades\\Individual_saccade_database.csv")

driving_perf_by_distance <- read_csv("G:\\Team Drives\\Research Team\\Projects\\2018 Driving Sim Reproducibility\\binned_by_dist_100_final.csv")

driving_perf_by_saccade <- read_csv("G:\\Team Drives\\Research Team\\Projects\\2018 Driving Sim Reproducibility\\binned_by_saccade_100_final.csv")

filtered_driving_perf_by_distance <- read_csv("G:\\Team Drives\\Research Team\\Projects\\2018 Driving Sim Reproducibility\\binned_by_dist_100_filtered_final.csv")

## ER is missing all trials requiring a right trigger response in Fam S1    
attention_performance_database <- read_csv("G:\\Team Drives\\Research Team\\Projects\\2018 Driving Sim Reproducibility\\task_response_database.csv") %>% 
            select(ID, Session, Run, `trial number`, task_condition, task_arrow_dir, stimulus_left_right, congruency, target_deviation, response_type,
                   reaction_time)

# creates a file where task performance data is given to the saccade data
saccade_attn_joined <- saccades_database %>% 
                        left_join(attention_performance_database, 
                                  by = c("ID","Session","Run","trial number")) %>% 
                        select(ID,Session,Run,`trial number`,condition, task_condition, eye, 
                               stimulus_left_right, task_arrow_dir, congruency,target_deviation,
                               `correct direction`, duration, `dva/s`, `peak_dva/s`, amplitude, saccade_size, `stimulus onset delay`,
                               reaction_time, response_type) 

KSS_data <- read_excel(path = "G:\\Team Drives\\Research Team\\Projects\\2018 Driving Sim Reproducibility\\KSS Scores.xlsx", sheet = 1) %>%
                select(1:7) %>% 
                gather(key = "Timepoint", value =  "kss_score", Baseline, Run_1, Run_2, Run_3, Run_4) %>%
                dplyr::filter(kss_score != "NA") %>% 
                as.tibble()

KSS_data$kss_score <- KSS_data$kss_score %>% as.numeric()
KSS_data$Timepoint <- KSS_data$Timepoint %>% as.factor()

```


#Plotting and summary of the KSS Data


```{r, echo=FALSE}


KSS_data %>% select(Session,Timepoint, Participant_ID,kss_score) %>%
    group_by(Session, Timepoint) %>% 
    summarise(mean = mean(kss_score), sd = sd(kss_score),sem = sd(kss_score)/sqrt(n())) %>%
    ggplot(aes(x = Timepoint, y= mean, shape = Session, group = Session)) +
    geom_point(size = 2) +
    geom_line(size = .5) +
    labs(title = "KSS Scores",
         x = " Timepoint",
         y = "Mean KSS Score") +
    scale_y_continuous(limits = c(1,9), breaks = c(1,2,3,4,5,6,7,8,9), expand = c(0,0)) +
    scale_x_discrete(labels = c("Baseline","Run 1","Run 2", "Run 3","Run 4"))+
    geom_errorbar(aes(ymin = mean - sem, ymax = mean + sem, width = .1)) +
    theme_classic()
    

kss_summary <- KSS_data %>% select(Session,Timepoint, Participant_ID,kss_score) %>%
    group_by(Session, Timepoint) %>% 
    summarise(mean = mean(kss_score), sd = sd(kss_score),sem = sd(kss_score)/sqrt(n()))

kss_fit <- aov(kss_score ~ Session * Timepoint, data = KSS_data)
summary(kss_fit)

kss_lm <- lmer(kss_score ~ Session * Timepoint + (1|Participant_ID), data = KSS_data)
summary(kss_lm)


```


#Plotting and analysis of Drivesim Data

```{r}
driving_perf_by_distance$Trial <- driving_perf_by_distance$Trial %>% as.character()
driving_perf_by_distance$Trial <- driving_perf_by_distance$Trial %>% factor(levels = c("F","1","2"))
driving_perf_by_distance$Run <- driving_perf_by_distance$Run %>% factor()

driving_perf_by_distance %>% group_by(Trial, Run, bin_number) %>% select (7:16) %>% summarise_at(vars(avg_speed:sd_steering),list(mean = ~mean(.),sd = ~sd(.),sem = (~sd(.)/sqrt(n())))) %>% arrange(Trial)

drive_perf_summary <- driving_perf_by_distance %>% group_by(Trial, Run, bin_number) %>% select (7:16) %>% summarise_at(vars(avg_speed:sd_steering),list(mean = ~mean(.),sd = ~sd(.),sem = (~sd(.)/sqrt(n())))) %>% mutate(Timepoint = str_c(Trial,Run, sep = "_" )) %>% dplyr::filter(bin_number > 3)

filtered_driving_perf_by_distance$Trial <- filtered_driving_perf_by_distance$Trial %>% as.character()


filtered_driving_perf_by_distance %>% group_by(Trial, Run, bin_number) %>% select (7:19) %>% summarise_at(vars(avg_speed:sd_filt_lanepos),list(mean = ~mean(.),sd = ~sd(.),sem = (~sd(.)/sqrt(n())))) %>% arrange(Trial)

filtered_drive_perf_summary <- filtered_driving_perf_by_distance %>% group_by(Trial, Run, bin_number) %>% select (7:19) %>% summarise_at(vars(avg_speed:sd_filt_lanepos),list(mean = ~mean(.),sd = ~sd(.),sem = (~sd(.)/sqrt(n())))) %>% mutate(Timepoint = str_c(Trial,Run, sep = "_" )) %>% dplyr::filter(bin_number > 3)

filtered_drive_perf_summary$Trial <- filtered_drive_perf_summary$Trial %>% factor(levels = c("F","1","2"))
filtered_drive_perf_summary$Run <- filtered_drive_perf_summary$Run %>% factor()

mean_speed <- drive_perf_summary %>% ggplot(aes(x = bin_number, y = avg_speed_mean, 
                                  group = Timepoint, shape = Timepoint, colour = Timepoint)) +
                                  geom_point() +
                                  geom_line() +
                                  labs(title = "Average Speed",
                                       x = "Bin Number",
                                       y = "Average Speed (km/h)") +
                                  geom_errorbar(aes(ymin = avg_speed_mean - avg_speed_sem, 
                                                    ymax = avg_speed_mean + avg_speed_sem, width = .1)) +
                                  theme_classic()
mean_speed

mean_lanepos <- drive_perf_summary %>% ggplot(aes(x = bin_number, y = avg_lanepos_mean +6, 
                                  group = Timepoint, colour = Timepoint, shape = Timepoint)) +
                                  geom_line() +
                                  labs(title = "Lane Position",
                                       x = "Bin Number",
                                       y = "Lane Position (m)") +
                                  geom_path()+
                                  theme_classic()
    
mean_lanepos

filtered_lanepos <- filtered_drive_perf_summary %>% ggplot(aes(x = bin_number, y = ang_filt_lanepos_sd , 
                                  group = Timepoint, shape = Timepoint)) +
                                  geom_line() +
                                  geom_smooth( alpha = 0.3)+
                                  labs(title = "Lane Position",
                                       x = "Bin Number",
                                       y = "Lane Position (m)") +
                                  geom_path()+
                                  theme_classic()
filtered_lanepos

filtered_lanepos_variability_boxplot <- filtered_drive_perf_summary %>% 
    ggplot(aes(x = Trial, y = sd_filt_lanepos_mean, fill = Run)) +
        geom_boxplot(outlier.shape = NA, size = .7, color = "black",fatten = .9)+
        stat_boxplot(geom = "errorbar", aes(ymax = ..ymax..)) +
        stat_boxplot(geom = "errorbar", aes(ymin = ..ymin..)) +
        ylab("SD of Lane Position (m)")+
        scale_y_continuous(limits = c(0,.5), expand = c(0,0.4))+
        scale_fill_grey(start = 0.4)+
        theme_classic()+
        theme(legend.key.size = unit(2.5,"line"),strip.background = element_blank(), 
              axis.line = element_line(size = .7), axis.ticks = element_line(size = .7), 
              text = element_text(size = 12))
    
filtered_lanepos_variability_boxplot

unfiltered_lanepos_var_boxplot <- drive_perf_summary %>% dplyr::filter(Trial != "F") %>%
    ggplot(aes(x = Trial, y = sd_lanepos_mean, fill = Run)) +
        geom_boxplot(outlier.shape = NA, size = .9, color = "black",fatten = 1)+
        stat_boxplot(geom = "errorbar", aes(ymax = ..ymax..), size = .9) +
        stat_boxplot(geom = "errorbar", aes(ymin = ..ymin..), size = 0.9) +
        ylab("SD of Lane Position (m)")+
        scale_y_continuous(limits = c(0,2), expand = c(0,0))+
        scale_fill_grey(start = 0.4)+
        theme_classic()+
        theme(legend.key.size = unit(2.5,"line"), 
              axis.line = element_line(size = .8), axis.ticks = element_line(size = .8), 
              text = element_text(size = 14))

unfiltered_lanepos_var_boxplot
ggsave(filename = "Analysis Figures\\unfiltered_lanepos_var_boxplot.eps", 
       unfiltered_lanepos_var_boxplot, dpi = 600, device = "eps", width =  10, height = 7)

unfiltered_avg_Speed_boxplot <- drive_perf_summary %>% dplyr::filter(Trial != "F") %>%
    ggplot(aes(x = Trial, y = avg_speed_mean, fill = Run)) +
        geom_boxplot(outlier.shape = NA, size = .9, color = "black",fatten = 1)+
        stat_boxplot(geom = "errorbar", aes(ymax = ..ymax..), size = .9) +
        stat_boxplot(geom = "errorbar", aes(ymin = ..ymin..), size = 0.9) +
        ylab("Average Speed (km/h)")+
        scale_y_continuous(limits = c(96,101), expand = c(0,0))+
        scale_fill_grey(start = 0.4)+
        theme_classic()+
        theme(legend.key.size = unit(2.5,"line"), 
              axis.line = element_line(size = .8), axis.ticks = element_line(size = .8), 
              text = element_text(size = 14))

unfiltered_avg_Speed_boxplot
ggsave(filename = "Analysis Figures\\unfiltered_avg_Speed_boxplot.eps", 
       unfiltered_avg_Speed_boxplot, dpi = 600, device = "eps", width =  10, height = 7)

unfiltered_avg_Speed_violin <- drive_perf_summary %>% dplyr::filter(Trial != "F") %>%
    ggplot(aes(x = Trial, y = avg_speed_mean, fill = Run)) +
        geom_violin(outlier.shape = NA, size = .9, color = "black",fatten = 1)+
        stat_summary(fun.data=mean_sdl, mult=1,geom="pointrange") +
        ylab("Average Speed (km/h)")+
        scale_y_continuous(limits = c(96,101), expand = c(0,0))+
        scale_fill_grey(start = 0.4)+
        theme_classic()+
        theme(legend.key.size = unit(2.5,"line"), 
              axis.line = element_line(size = .8), axis.ticks = element_line(size = .8), 
              text = element_text(size = 14))

unfiltered_avg_Speed_violin

drive_perf_summary$Run <- drive_perf_summary$Run %>% as.factor()

ridgeline_speed_avg <- drive_perf_summary %>%
    ggplot(aes(x = avg_speed_mean, y = Trial, 
               color = Run, point_color = Run, 
               fill = Run, height = ..density..)) + 
    geom_density_ridges(jittered_points = FALSE, quantile_lines = TRUE, scale = 0.7, 
                      alpha = 0.1, vline_size = .5, vline_color = c("black"), point_size = 0.4,
                      position = position_raincloud(adjust_vlines = FALSE)) +
    stat_density_ridges(quantile_lines = TRUE, alpha = 0.2, scale = .7) +
    scale_color_cyclical(values = c("blue", "red"))+
    scale_fill_cyclical(values = c("blue", "red"), guide = "legend",
                        labels = c("Run 1", "Run 2"))+
    theme_classic()

ridgeline_speed_avg


```



```{r}
ridgeline_speed_avg_of_sd <- drive_perf_summary %>%
    ggplot(aes(x = sd_speed_mean, y = Trial, 
               color = Run, point_color = Run, 
               fill = Run, height = ..density..)) + 
    geom_density_ridges(jittered_points = FALSE, quantile_lines = TRUE, scale = 0.7, 
                      alpha = 0.1, vline_size = .5, vline_color = c("black"), point_size = 0.4,
                      position = position_raincloud(adjust_vlines = FALSE)) +
    stat_density_ridges(quantile_lines = TRUE, alpha = 0.2, scale = .7) +
    scale_color_cyclical(values = c("blue", "red"))+
    scale_fill_cyclical(values = c("blue", "red"), guide = "legend",
                        labels = c("Run 1", "Run 2"))+
    theme_classic()

ridgeline_speed_avg_of_sd 
```


Attention task Data

```{r}
##Overall Performance
attn_analysis <- attention_performance_database %>% 
    group_by(ID, Session, Run, target_deviation) %>%
    summarise(mean_RT = mean(reaction_time), 
              sd_RT = sd(reaction_time), 
              count = n(),
              percent_correct = mean(response_type == "Correct", na.rm = TRUE), 
              percent_miss = mean(response_type == "Miss", na.rm = TRUE),
              percent_incorrect = mean(response_type == "Incorrect", na.rm = TRUE)) %>%
    mutate(Timepoint = str_c(Session,Run, sep = "_"))
attn_analysis




##Performance based on congruency
attn_analysis_withcongruency <- attention_performance_database %>%
    group_by(ID, Session, Run, congruency, target_deviation) %>% 
    summarise(mean_RT = mean(reaction_time), 
              sd_RT = sd(reaction_time), 
              count = n(),
              percent_correct = mean(response_type == "Correct", na.rm = TRUE), 
              percent_miss = mean(response_type == "Miss", na.rm = TRUE),
              percent_incorrect = mean(response_type == "Incorrect", na.rm = TRUE)) %>%
    mutate(Timepoint = str_c(Session,Run, sep = "_"))

attn_analysis_withcongruency

attention_performance_database$Session <- factor(attention_performance_database$Session, levels = c("F","1", "2"))

attention_performance_database$Run <- factor(attention_performance_database$Run, levels = c("1", "2"))


attention_RT_boxplot <- attention_performance_database %>% 
    mutate(Timepoint = str_c(Session,Run, sep = "_")) %>%
    filter(response_type == "Correct") %>% 
    filter(Session != "F") %>%
    ggplot(aes(x = Session, y = reaction_time, fill = Run)) +
    geom_boxplot(outlier.shape = NA, size = .8, color = "black",fatten = .9)+
        stat_boxplot(geom = "errorbar", aes(ymax = ..ymax..)) +
        stat_boxplot(geom = "errorbar", aes(ymin = ..ymin..)) +
        ylab("Reaction time(s)")+
        scale_y_continuous(limits = c(0,1.5), expand = c(0,0))+
        scale_fill_grey(start = 0.4)+
        theme_classic()+
        theme(legend.key.size = unit(2.5,"line"), strip.background = element_blank(), 
              axis.line = element_line(size = .8), axis.ticks = element_line(size = .8), 
              text = element_text(size = 13))+
        facet_wrap(~congruency)
attention_RT_boxplot

dggsave(filename = "Analysis Figures\\Attention_RT_boxplot_bycongruency.eps", 
       attention_RT_boxplot, dpi = 600, device = "eps", width =  10, height = 7)

attention_performance_database %>% mutate(Timepoint = str_c(Session,Run, sep = "_")) %>%
    filter(response_type == "Correct") %>% 
    filter(Session != "F") %>% 
    group_by(ID, Run, Session, congruency) %>%
    summarise(n(), mean_RT = mean(reaction_time), sd_RT = sd(reaction_time)) %>%
    write.csv(file = "Analysis csvs/attention_taskperf_reactiontime.csv")

attention_performance_database %>%
    filter(Session != "F") %>% 
    group_by(ID, Run, Session, congruency, response_type) %>%
    summarise(n())

task_accuracy_bar <- attention_performance_database %>%
    dplyr::filter(Session != "F") %>% 
    dplyr::filter(!is.na(response_type)) %>%
    mutate(Timepoint = factor(str_c(Session,Run, sep = "_"))) %>%
    ggplot(aes(x = response_type, group = Timepoint, fill = response_type))+
        geom_bar(position = "dodge",aes(y = ..prop.., fill= factor(response_type), stat = "count")) +
        scale_y_continuous(labels = scales::percent_format()) +
        scale_fill_grey(start = 0.2, end = 0.7)+
        theme_classic()+
        theme(legend.key.size = unit(2.5,"line"),strip.background = element_blank(), 
              axis.line = element_line(size = .7), axis.ticks = element_line(size = .7), 
              text = element_text(size = 12))+
        facet_wrap(~Timepoint, nrow = 1, strip.position = "bottom")

task_accuracy_bar

prop_correct_line <- attention_performance_database %>%
    dplyr::filter(Session != "F") %>% 
    dplyr::filter(response_type == "correct") %>%
    mutate(Timepoint = factor(str_c(Session,Run, sep = "_"))) %>%
    ggplot(aes(x = Timepoint))+
    geom_point(aes(y = prop))

attention_performance_database$ID <- factor(attention_performance_database$ID)
task_accuracy_props <- attention_performance_database %>%
    dplyr::filter(response_type != "NA") %>% 
    group_by(ID, Session, Run) %>% 
    count(response_type) %>%
    mutate(proportion = prop.table(n)) %>%
    mutate(Timepoint = factor(str_c(Session,Run, sep = "_")))
    

task_accuracy_props

```

#Saccade Performance Analysis

```{r}

saccade_attn_joined <- saccade_attn_joined %>% mutate(Timepoint = factor(str_c(Session,Run, sep = "_")))
names(saccade_attn_joined)

organised_saccade_data <- saccade_attn_joined %>% dplyr::filter(amplitude > 2)
organised_saccade_data$saccade_bin <- if_else((organised_saccade_data$amplitude > 2) & (organised_saccade_data$amplitude < 15), "5-15",
                                         if_else((organised_saccade_data$amplitude > 15) & (organised_saccade_data$amplitude < 25), "20-30",
                                         if_else((organised_saccade_data$amplitude > 25) & (organised_saccade_data$amplitude < 40), "30-40","NA"))) %>% as.factor()
organised_saccade_data$saccade_bin <- organised_saccade_data$saccade_bin %>% factor(levels = c("5-15","20-30","30-40", "NA"))
organised_saccade_data$Run <- factor(organised_saccade_data$Run)

organised_saccade_data %>% dplyr::filter(saccade_bin != "NA") %>% group_by(Timepoint,saccade_bin) %>% summarise(n())

saccade_velocity_by_amplitude <- organised_saccade_data %>% 
    dplyr::filter(saccade_bin != "NA") %>% 
    dplyr::filter(Session != "F") %>% 
    dplyr::filter(`peak_dva/s` <= 1200) %>%
    ggplot(aes(x = Session, y = `peak_dva/s`, fill = Run)) +
        geom_boxplot(outlier.shape = NA, size = .7, color = "black",fatten = .9)+
        stat_boxplot(geom = "errorbar", aes(ymax = ..ymax..)) +
        stat_boxplot(geom = "errorbar", aes(ymin = ..ymin..)) +
        ylab("Peak Saccade Velocity (\u00B0/s)")+
        scale_y_continuous(limits = c(0,1000), expand = c(0,0.4))+
        scale_fill_grey(start = 0.4)+
        theme_classic()+
        theme(legend.key.size = unit(2.5,"line"),strip.background = element_blank(), 
              axis.line = element_line(size = .7), axis.ticks = element_line(size = .7), 
              text = element_text(size = 12))+
        facet_wrap(~saccade_bin) 


saccade_velocity_by_amplitude   
ggsave(filename = "Analysis Figures\\Saccade_boxplot_byamplitudes.eps", 
       saccade_velocity_by_amplitude, dpi = 600, device = "eps", width =  10, height = 7)

organised_saccade_data %>% 
    dplyr::filter(saccade_bin != "NA") %>% 
    dplyr::filter(Session != "F") %>% 
    dplyr::filter(`peak_dva/s` <= 1200) %>%
    group_by(ID,Timepoint,saccade_bin) %>% 
    summarise(n(), avg_peak = mean(`peak_dva/s`), sd_peak = sd(`peak_dva/s`), 
              avg_meanvel = mean(`dva/s`), sd_meanvel = sd(`dva/s`)) %>% 
    write.csv(file = "Analysis csvs/saccade summary by bin.csv")


saccade_mean_velocity_by_amplitude <- organised_saccade_data %>% 
    dplyr::filter(saccade_bin != "NA") %>% 
    dplyr::filter(Session != "F") %>% 
    dplyr::filter(`dva/s` <= 1000) %>%
    ggplot(aes(x = Session, y = `dva/s`, fill = Run)) +
        geom_boxplot(outlier.shape = NA, size = .7, color = "black",fatten = .9)+
        stat_boxplot(geom = "errorbar", aes(ymax = ..ymax..)) +
        stat_boxplot(geom = "errorbar", aes(ymin = ..ymin..)) +
        ylab("Peak Saccade Velocity (\u00B0/s)")+
        scale_y_continuous(limits = c(0,600), expand = c(0,0.4))+
        scale_fill_grey(start = 0.4)+
        theme_classic()+
        theme(legend.key.size = unit(2.5,"line"),strip.background = element_blank(), 
              axis.line = element_line(size = .7), axis.ticks = element_line(size = .7), 
              text = element_text(size = 12))+
        facet_wrap(~saccade_bin) 


saccade_mean_velocity_by_amplitude   
ggsave(filename = "Analysis Figures\\Saccade_meanvelocity_boxplot_byamplitudes.eps", 
       saccade_mean_velocity_by_amplitude, dpi = 600, device = "eps", width =  10, height = 7)


```

