---
title: "Reliability Analysis"
author: "Hayden Green"
date: "11 October 2018"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidyselect)
library(ggthemes)
library(ggridges)
library(xlsx)
library(psy)
library(psych)
library(irr)
library(ez)
library(data.table)
library(blandr)

file_to_import <- list.files(path = "G:/Team Drives/Research Team/Projects/2018 Driving Sim Reproducibility/", pattern = "?KSS Scores.xlsx", recursive = TRUE, full.names = TRUE)

KSS_scores <- read_excel("G:/Team Drives/Research Team/Projects/2018 Driving Sim Reproducibility/KSS Scores.xlsx")

KSS_scores %>% head()

gathered <- KSS_scores %>% gather(Baseline:Run_4, key = "Variable", value = "value")
gathered$Variable <- gathered$Variable %>% as.character() 

na_removed <- gathered %>% 
  filter(value != "NA") %>% 
  filter(Variable != "Run_3"| Variable != "Run_4") 
na_removed$value <- na_removed$value %>% as.numeric()

na_removed %>% head()

```


```{r}

KSSfit1 <- aov(value ~ Session*Variable + Participant_ID, na_removed)
summary(KSSfit1)

ezANOVA(na_removed, dv = value, wid = Participant_ID, within = .(Variable, Session), detailed = TRUE)


```

```{r}

binned_files_saccade <- list.files(path = "G:/Team Drives/Research Team/Projects/2018 Driving Sim Reproducibility/", pattern = "?binned_by_saccade_100", recursive = TRUE, full.names = TRUE)

binned_files_distance <- list.files(path = "G:/Team Drives/Research Team/Projects/2018 Driving Sim Reproducibility/", pattern = "?binned_by_dist_100", recursive = TRUE, full.names = TRUE)


database_by_distance <- binned_files_distance %>% map_df(~create_database_dist(.))
database_by_distance$Run <- database_by_distance$Run %>% as.factor()

database_by_saccade <- binned_files_saccade %>% map_df(~create_database_saccade(.) )
database_by_saccade$Run <- database_by_saccade$Run %>% as.factor()

create_database_dist <- function (x) {
  
        df <- read_csv(x, col_types = "???????????????????c?d?")

        df$ID <- df$ID %>% as.character()
        df$File_Number <- df$File_Number %>% as.double()
        df$Date <- df$Date %>% as.Date()
        df$Trial <- df$Trial %>% as.character()
        df$Run <- df$Run %>% as.character()
        df1 <- df %>% filter(start_dist < 30001, start_dist > 299)
        df1
            }



create_database_saccade <- function (x) {     
        df <- read_csv(x, col_types = "???????????????????c?d")

        df$ID <- df$ID %>% as.character()
        df$File_Number <- df$File_Number %>% as.double()
        df$Date <- df$Date %>% as.Date()
        df$Trial <- df$Trial %>% as.character()
        df$Run <- df$Run_Number %>% as.character()
        df1 <- df
        df1
  }

Fam <- database_by_saccade %>% filter(Trial == "F" & Run == 1) %>% arrange(ID, Run, saccade_number)

T1_R1 <-  database_by_saccade %>% filter(Trial == "1" & Run == 1) %>% arrange(ID,Run,saccade_number)


T1_R2 <-  database_by_saccade %>% filter(Trial == "1" & Run == 2) %>% arrange(ID,Run,saccade_number)

T2_R1 <-  database_by_saccade %>% filter(Trial == "2" & Run == 1) %>% arrange(ID,Run,saccade_number) 

T2_R2 <-  database_by_saccade %>% filter(Trial == "2" & Run == 2) %>% arrange(ID,Run,saccade_number)



#Fam <- Fam %>% group_by(ID) %>% summarise(min = min(bin_number), max = max(bin_number), mean_lanesd = mean(sd_speed))
#T1_R1 <- T1_R1 %>% group_by(ID) %>% summarise(min = min(bin_number), max = max(bin_number), mean_lanesd = mean(sd_speed))
#T1_R2 %>% group_by(ID,bin_number) %>% summarise(min = min(bin_number), max = max(bin_number), mean_lanesd = mean(sd_speed))
#T2_R1 %>% group_by(ID,bin_number) %>% summarise(min = min(bin_number), max = max(bin_number), mean_lanesd = mean(sd_speed))
#T2_R2 %>% group_by(ID,bin_number) %>% summarise(min = min(bin_number), max = max(bin_number), mean_lanesd = mean(sd_speed))



 Fam_t_test <- Fam   %>% group_by(ID) %>% summarise(var = abs(mean(sd_throttle))*1000)
 T1_R1_t_test <- T1_R1 %>% group_by(ID) %>% summarise(var = abs(mean(sd_throttle))*1000)
 T1_R2_t_test <- T1_R2 %>% group_by(ID) %>% summarise(var = abs(mean(sd_throttle))*1000)
 T2_R1_t_test <- T2_R1 %>% group_by(ID) %>% summarise(var = abs(mean(sd_throttle))*1000)
 T2_R2_t_test <- T2_R2 %>% group_by(ID) %>% summarise(var = abs(mean(sd_throttle))*1000)
 
 Fam_onlyT2 <- Fam %>% filter(ID == Completed_T2) %>% group_by(ID) %>% summarise(var = abs(mean(sd_throttle))*1000)
 T1_R1_onlyT2 <-T1_R1 %>% filter(ID == Completed_T2) %>% group_by(ID) %>% summarise(var = abs(mean(sd_throttle))*1000)
 T1_R2_onlyT2 <- T1_R2 %>% filter(ID == Completed_T2) %>% group_by(ID) %>% summarise(var = abs(mean(sd_throttle))*1000)
 
 
 
variables <- names(Fam)[6:16]

Completed_T2 <- T2_R1$ID %>% unique()

Timepoints <- c("Fam", "T1_R1", "T1_R2", "T2_R1", "T2_R2")

summarydata <- data.frame(time = Timepoints, mean = 1:5, sd = 1:5)

summarydata$mean <- c(mean(Fam_t_test$var), mean(T1_R1_t_test$var),
                      mean(T1_R2_t_test$var), mean(T2_R1_t_test$var),
                      mean(T2_R2_t_test$var))

summarydata$sd <- c(sd(Fam_t_test$var), sd(T1_R1_t_test$var),
                      sd(T1_R2_t_test$var), sd(T2_R1_t_test$var),
                      sd(T2_R2_t_test$var))

```

```{r} 
 ##Fam Vs T1_R1
 Fam_vs_T1difference <- Fam_t_test$var - T1_R1_t_test$var
 Fam_vs_T1logdifference <- log(Fam_t_test$var) - log(T1_R1_t_test$var)
  
 shapiro.test(Fam_vs_T1difference)
 shapiro.test(Fam_vs_T1logdifference)
 t.test(Fam_t_test$var, T1_R1_t_test$var, paired = TRUE)
 t.test(log(Fam_t_test$var), log(T1_R1_t_test$var), paired = TRUE)
 psych::ICC(data_frame(Fam_t_test$var, T1_R1_t_test$var))
 
 wilcox.test(Fam_t_test$var, T1_R1_t_test$var, paired = TRUE)
```

```{r}
 
 ##T1_R1 vs T1_R2
 T1R1_vs_T1R2difference <- T1_R1_t_test$var - T1_R2_t_test$var
 T1R1_vs_T1R2logdifference <- log(T1_R1_t_test$var) - log(T1_R2_t_test$var)
 shapiro.test(T1R1_vs_T1R2difference)
 shapiro.test(T1R1_vs_T1R2logdifference)
 
 t.test(T1_R1_t_test$var,T1_R2_t_test$var, paired = TRUE)
 t.test(log(T1_R1_t_test$var),log(T1_R2_t_test$var), paired = TRUE)
 psych::ICC(data_frame(T1_R1_t_test$var,T1_R2_t_test$var))
 blandr.display.and.draw(T1_R1$sd_steering,T1_R2$sd_steering)

 data <- data_frame(T1_R1_t_test$var,T1_R2_t_test$var)
 
 ggplot(data = data_frame(T1_R1_t_test$var,T1_R2_t_test$var),aes(x = T1_R1_t_test$var, y = T1_R2_t_test$var))+ geom_point() + xlim(2,3) + ylim(2,3)
```
 
```{r} 
##Fam vs T2_R1 difference 
 Fam_vs_T2R1difference <- Fam_onlyT2$var - T2_R1_t_test$var
 Fam_vs_T2R1logdifference <- log(Fam_onlyT2$var) - log(T2_R1_t_test$var)
 shapiro.test(Fam_vs_T2R1difference)
 shapiro.test(Fam_vs_T2R1logdifference)
 
 t.test(Fam_onlyT2$var,T2_R1_t_test$var, paired = TRUE)
 t.test(log(Fam_onlyT2$var),log(T2_R1_t_test$var), paired = TRUE)
 psych::ICC(data_frame(Fam_onlyT2$var,T2_R1_t_test$var))

``` 
 
```{r}
  
 ## T1_R1 vs T2_R1
 T1_R1_vs_T2_R1difference <- T1_R1_onlyT2$var - T2_R1_t_test$var
 T1_R1_vs_T2_R1logdifference <- log(T1_R1_onlyT2$var) - log(T2_R1_t_test$var)
 shapiro.test(T1_R1_vs_T2_R1difference)
 shapiro.test(T1_R1_vs_T2_R1logdifference) 
 
 t.test(T1_R1_onlyT2$var,T2_R1_t_test$var, paired = TRUE)
 t.test(log(T1_R1_onlyT2$var),log(T2_R1_t_test$var), paired = TRUE)
 psych::ICC(data_frame(T1_R1_onlyT2$var,T2_R1_t_test$var))
```

```{r}  
 ## T1_R2 vs T2_R2
 T1_R2_vs_T2_R2difference <- T1_R2_onlyT2$var - T2_R2_t_test$var
 T1_R2_vs_T2_R2logdifference <- log(T1_R2_onlyT2$var) - log(T2_R2_t_test$var)
 shapiro.test(T1_R2_vs_T2_R2difference)
 shapiro.test(T1_R2_vs_T2_R2logdifference)$p.value
 
 t.test(T1_R2_onlyT2$var,T2_R2_t_test$var, paired = TRUE)
 t.test(log(T1_R2_onlyT2$var),log(T2_R2_t_test$var), paired = TRUE)
 psych::ICC(data_frame(T1_R2_onlyT2$var,T2_R2_t_test$var))
 
 wilcox.test(T1_R2_onlyT2$var,T2_R2_t_test$var, paired = TRUE)
 
``` 
 
```{r} 
 ##T2_R1 vs T2_R2
 T2_R1_vs_T2R2difference <- T2_R1_t_test$var - T2_R2_t_test$var
 T2_R1_vs_T2R2logdifference <- log(T2_R1_t_test$var) - log(T2_R2_t_test$var)
 shapiro.test(T2_R1_vs_T2R2difference)
 shapiro.test(T2_R1_vs_T2R2logdifference)
 
 t.test(T2_R1_t_test$var,T2_R2_t_test$var, paired = TRUE)
 t.test(log(T2_R1_t_test$var),log(T2_R2_t_test$var), paired = TRUE)
 psych::ICC(data_frame(T2_R1_t_test$var,T2_R2_t_test$var))
 
 blandr.display.and.draw(T2_R1$sd_steering,T2_R2$sd_steering)
``` 

```{r}

aov(Fam_onlyT2[var],T1_R1_onlyT2$var,T2_R1_t_test$var)

```



```{r}

psych::ICC(data_frame(Fam_onlyT2$var,T1_R1_onlyT2$var,T2_R1_t_test$var))

```


```{r}
##ridgeline plot with median upper and lower quartiles, can change stat_density_ridges(quantile_lines = TRUE, quantiles = c() ) and then 
p1 <- ggplot(x, aes(x = avg_lanepos, y = Trial, height = ..density.., fill = Run)) +
    stat_density_ridges(quantile_lines = TRUE, alpha = 0.9, scale = .9) +
  theme_minimal()
p1
# an alternative ridgeline plot with data points recorded can use in aes(color = Run_Number once correctly labelled run number to 1 or two)


  p2 <- ggplot(database_by_saccade, aes(x = sd_speed, y = Trial, height = ..density..)) +
  geom_density_ridges(jittered_points = TRUE, quantile_lines = TRUE, scale = 0.9, 
                      alpha = 0.5, vline_size = .8, vline_color = "blue", point_size = 0.4,
                      position = position_raincloud(adjust_vlines = FALSE)) +
  theme_classic()
p2


ridgeline_with_dots(df = x, variable_to_show = sd_speed)



p3 <- ggplot(database_by_saccade, aes(x = sd_steering, y = Trial, color = Run, point_color = Run, fill = Run, height = ..density..)) + geom_density_ridges(jittered_points = FALSE, quantile_lines = TRUE, scale = 0.7, 
                      alpha = 0.1, vline_size = .5, vline_color = c("black"), point_size = 0.4,
                      position = position_raincloud(adjust_vlines = FALSE)) +
    stat_density_ridges(quantile_lines = TRUE, alpha = 0.2, scale = .7) +
    scale_color_cyclical(values = c("blue", "red"))+
    scale_fill_cyclical(values = c("blue", "red"), guide = "legend",
                        labels = c("Run 1", "Run 2"))+
    xlab("Variability of Steering Input (AU)")+
  theme_classic()
 
p3

ggpath <- "G:\\Team Drives\\Research Team\\Projects\\2018 Driving Sim Reproducibility\\Prelim Figures\\"
    
ggsave(filename = "sd_steering.png", plot = p3, path = ggpath, device = "png", width = 15, height = 10, units = "cm", dpi = 400)

```



```{r}



blandr.draw(Fam$sd_speed,T1_R1$sd_speed, LoA.mode = 1) + theme_bw()
```

