---
title: "R Notebook"
output: html_notebook
---


```{r, results='hide'}

library(tidyverse)
library(readxl)
library(lme4)
library(lmerTest)
library(psych)

```

Get the Reference Database

```{r}
 
Filename_Database <- read_excel("G:/Team Drives/Research Team/Projects/2018 Driving Sim Reproducibility/File Reference Database.xlsx", 
                                 sheet = 1)

Country_database <- Filename_Database %>% filter(Scenario == "Country")


find_saccade_csv_filename <- function(x) {
   y <-  list.files(path = "G:\\Team Drives\\Research Team\\Projects\\2018 Driving Sim Reproducibility\\4_Analysis_Saccades\\", 
           pattern = paste0(x,"_Prosaccade_final.csv"), 
           full.names = TRUE, recursive = TRUE)
    z <- if_else(length(y) == 0, "NA", y[1]) %>% as.character()
     z
    }


Country_database$final_csvs <- Country_database$Saccade_pattern %>% lapply(find_saccade_csv_filename)

importing_df <- Country_database %>% select(Participant, Session, Run, final_csvs)


```

Load the Data

```{r}

create_database_saccades <- function (Participant, Session, Run, final_csvs) {
   
 filename <- final_csvs %>% as.character()   
  df <- read_csv(filename)
  df$ID <- Participant %>% as.character()
  df$Session <- Session %>% as.character()
  df$Run <- Run %>% as.character()
  
 
 select_one_saccade <- function(df1) {
    eye_1 <- df1 %>% filter(eye == 1) %>% count() %>% as.numeric()
    eye_2 <- df1 %>% filter(eye == 2) %>% count() %>% as.numeric()
    eye_1_or_2 <- if_else(eye_1 > eye_2, 1, 2)
    
    duplicate <- df1 %>% group_by(`trial number`) %>%  summarise(n = n()) %>% mutate(duplicate = if_else(n == 2, 1, 0)) %>% select(-2)
    
    df1 <- left_join(df1, duplicate, by = "trial number")
    df1$include <- if_else(df1$duplicate == 0, 1,
                          if_else(df1$duplicate == TRUE & df1$eye == eye_1_or_2, 1, 0))
    
    df2 <- df1 %>% filter(include == 1)
    df2
 }
 
 select_one_saccade(df)
 }

saccades_database <- importing_df %>% 
    filter(final_csvs != "NA") %>%
    pmap_df(~create_database_saccades(..1,..2,..3,..4))

saccades_database <- saccades_database %>% filter(is.double(`peak_dva/s`)) %>% filter(`peak_dva/s` < 2000) %>% filter(`dva/s` < 2000)

saccades_database$saccade_size <- if_else((saccades_database$amplitude >7.5) & (saccades_database$amplitude < 12.5), "10",
                                         if_else((saccades_database$amplitude > 22.5) & (saccades_database$amplitude < 27.5), "25",
                                         if_else((saccades_database$amplitude > 32.5) & (saccades_database$amplitude < 37.5), "35","NA")))



write_csv(saccades_database, file.choose())

```

sifting down the data

```{r}
saccades_database <- (read_csv("G:\\Team Drives\\Research Team\\Projects\\2018 Driving Sim Reproducibility\\4_Analysis_Saccades\\Individual_saccades_database.csv"))

summarised <- saccades_database %>% 
    filter(`peak_dva/s` < 2000) %>%
    filter(`dva/s` < 2000) %>%
    group_by(ID, Session, Run) %>%
    select(ID, Session, Run,`trial number`, `peak_dva/s`, `dva/s`, amplitude) %>% 
    summarise(peak_V = mean(`peak_dva/s`), avg_V = mean(`dva/s`), amplitude = mean(amplitude))


working_csv <- "G:\\Team Drives\\Research Team\\Projects\\2018 Driving Sim Reproducibility\\4_Analysis_Saccades\\working_csv.csv"
write_csv(summarised, path = working_csv)

lm1 <- lmer(peak_V ~ Run + Session + Run*Session + amplitude + (1|ID), data = summarised, na.action = na.exclude)
summary(lm1)


lm2 <- lmer(`dva/s` ~ Run*Session + amplitude + (1|ID), data = saccades_database, na.action = na.exclude)
summary(lm2)
plot(lm1)

summarised$Session <- summarised$Session %>% as.factor()
summarised$Run <- summarised$Run %>% as.factor()
head(summarised)
```

Statistical analyses

```{r}

saccade_database_for_SPSS <- saccades_database %>% select()


```

